//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class SweepPKFPort : BaseFPort
{ 
	private CallBack callback;
		
	public void getPK (CallBack callback)
	{  
		this.callback = callback;
		ErlKVMessage message = new ErlKVMessage (FrontPort.SWEEP_PK);
		access (message);
	}
		
	public override void read (ErlKVMessage message)
	{
		if (callback != null) {
			callback ();
			callback = null;
		}
	}
}


