//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

public class MonthCardSampleManager :ConfigManager
{

	private static MonthCardSampleManager _Instance;
	private static bool _singleton = true;
	
	public MonthCardSampleManager()
	{
		if (_singleton)
			return;
		base.readConfig(ConfigGlobal.CONFIG_MONTH_CARD);
	}
	
	public static MonthCardSampleManager Instance
	{
		get
		{
			
			if (_Instance == null)
			{
				_singleton = false;
				_Instance = new MonthCardSampleManager();
				_singleton = true;
				return _Instance;
			}
			else
				return _Instance;
		}
		set
		{
			_Instance = value;
		}
	}
	private List<PrizeSample> prizeSampleList;
	private Hashtable cardTable;
	private int vipRequestMinLevel;

	//解析配置文件 需要子类覆盖
	public override void parseConfig (string str)
	{
		string[] strArr=str.Split('|');
		parseCards(strArr[0]);
		parsePrizes(strArr[1]);
		vipRequestMinLevel=StringKit.toInt(strArr[2]);
	}
	private void parsePrizes(string str)
	{
		prizeSampleList=new List<PrizeSample>();
		PrizeSample item;
		string[] strArr=str.Split('#');
		for(int i=0,length=strArr.Length;i<length;i++)
		{
			item=new PrizeSample(strArr[i],',');
			prizeSampleList.Add(item);
		}
	}
	private void parseCards(string str)
	{
		cardTable=new Hashtable();
		MonthCardSample item;
		string[] strArr=str.Split('#');
		for(int i=0,length=strArr.Length;i<length;i++)
		{
			item=new MonthCardSample(strArr[i]);
			cardTable.Add(item.sid,item);
		}
	}
	/// <summary>
	/// VIP最低要求
	/// </summary>
	/// <returns>The minimum vip level.</returns>
	public int getVipRequestMinLevel()
	{
		return vipRequestMinLevel;
	}
	/// <summary>
	/// 返回月卡每天可获得的奖励
	/// </summary>
	/// <returns>The day reward.</returns>
	public List<PrizeSample> getDayReward()
	{
		return prizeSampleList;
	}
	/// <summary>
	/// 返回一个月卡信息
	/// </summary>
	/// <returns>The sample by identifier.</returns>
	/// <param name="sid">Sid.</param>
	public MonthCardSample getSampleById(int sid)
	{
		return cardTable[sid] as MonthCardSample;
	}
	/// <summary>
	/// 返回所有月卡
	/// </summary>
	/// <returns>The all sample identifiers.</returns>
	public int[] getAllSampleIds ()
	{ 
		List<int> list = new List<int> (); 
		foreach (int key in cardTable.Keys) {			
			list.Add ((int)key); 
		}
		return list.ToArray ();
	}


}


