//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class ArenaActivityInfo
{
	public EnumArena type=EnumArena.arena;
	public ArenaActivityInfo (EnumArena _type,int _requestMinLevel)
	{
		type=_type;
		requestMinLevel=_requestMinLevel;
		userRank=1;
		leftTimes=50;
		countdown=100000;
	}

	/// <summary>
	/// 要求开放等级
	/// </summary>
	private int requestMinLevel;
	public int RequestMinLevel {
		get {
			return requestMinLevel;
		}
	}

	private int userRank;
	public int UserRank {
		get {
			return userRank;
		}
	}

	private int leftTimes;
	public int LeftTimes {
		get {
			return leftTimes;
		}
	}

	private int countdown;
	public int Countdown {
		get {
			return countdown;
		}
	}

	/// <summary>
	/// 
	/// </summary>
	/// <param name="_userRank">玩家排名</param>
	/// <param name="_leftTimes">挑战次数</param>
	/// <param name="_countdown">倒计时.</param>
	public void M_setParameter_normal(int _userRank,int _leftTimes,int _countdown)
	{
		userRank=_userRank;
		leftTimes=_leftTimes;
		countdown=_countdown;
	}

	private int grounpId;
	public int GrounpId {
		get {
			return grounpId;
		}
	}

	public void M_setParamter_arena(int _grounpId)
	{
		grounpId=_grounpId;
	}
}

public enum EnumArena
{
	arena,
	ladders,
	mineral
}


